from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget


class KataQual_SecondWindow_Ui(object):
    def setupUi2(self, Form22):
        Form22.setObjectName("Form22")
        Form22.setEnabled(True)
        Form22.resize(1920, 1069)
        Form22.setWindowOpacity(1.0)
        Form22.setStyleSheet("background-color: rgb(255, 255, 255);")

        self.line2 = QtWidgets.QFrame(Form22)
        self.matchName2 = QtWidgets.QLabel(Form22)
        self.frame_white2 = QtWidgets.QFrame(Form22)
        self.label_name_white_2 = QtWidgets.QLabel(self.frame_white2)
        self.label_region_white_2 = QtWidgets.QLabel(self.frame_white2)
        self.frame_red2 = QtWidgets.QFrame(Form22)
        self.label_name_red_2 = QtWidgets.QLabel(self.frame_red2)
        self.label_region_red_2 = QtWidgets.QLabel(self.frame_red2)

        self.matchName2.setGeometry(QtCore.QRect(20, 10, 1880, 100))
        self.matchName2.setStyleSheet("font-family: Gotham-Medium; font-size: 75pt; color: grey;")
        self.matchName2.setAlignment(QtCore.Qt.AlignCenter)
        self.matchName2.setObjectName("matchName2")

        self.line2.setGeometry(QtCore.QRect(957, 40, 6, 1000))
        font = QtGui.QFont()
        font.setKerning(True)
        self.line2.setFont(font)
        self.line2.setLineWidth(1)
        self.line2.setMidLineWidth(6)
        self.line2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line2.setObjectName("line2")

        self.frame_white2.setGeometry(QtCore.QRect(1000, 40, 880, 1000))
        self.frame_white2.setStyleSheet("")
        self.frame_white2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_white2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_white2.setLineWidth(0)
        self.frame_white2.setObjectName("frame_white2")

        self.label_name_white_2.setGeometry(QtCore.QRect(30, 220, 800, 450))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_name_white_2.sizePolicy().hasHeightForWidth())
        self.label_name_white_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gotham")
        font.setPointSize(100)
        self.label_name_white_2.setFont(font)
        self.label_name_white_2.setAutoFillBackground(False)
        self.label_name_white_2.setStyleSheet("background-color: none;\n, color: black;")
        self.label_name_white_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_name_white_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_name_white_2.setLineWidth(1)
        self.label_name_white_2.setMidLineWidth(0)
        self.label_name_white_2.setScaledContents(False)
        self.label_name_white_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name_white_2.setObjectName("label_name_white_2")

        self.label_region_white_2.setGeometry(QtCore.QRect(30, 550, 800, 450))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_region_white_2.sizePolicy().hasHeightForWidth())
        self.label_region_white_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gotham")
        font.setPointSize(40)
        self.label_region_white_2.setFont(font)
        self.label_region_white_2.setAutoFillBackground(False)
        self.label_region_white_2.setStyleSheet("background-color: none;\n, color: ц;")
        self.label_region_white_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_region_white_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_region_white_2.setLineWidth(1)
        self.label_region_white_2.setMidLineWidth(0)
        self.label_region_white_2.setScaledContents(False)
        self.label_region_white_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_region_white_2.setObjectName("label_region_white_2")

        self.frame_red2.setGeometry(QtCore.QRect(40, 40, 880, 1000))
        self.frame_red2.setStyleSheet("background-color: rgb(255, 95, 95);")
        self.frame_red2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_red2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_red2.setObjectName("frame_red2")

        self.label_name_red_2.setGeometry(QtCore.QRect(40, 220, 800, 450))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_name_red_2.sizePolicy().hasHeightForWidth())
        self.label_name_red_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gotham")
        font.setPointSize(100)
        self.label_name_red_2.setFont(font)
        self.label_name_red_2.setAutoFillBackground(False)
        self.label_name_red_2.setStyleSheet("background-color: none;\n, color: white;")
        self.label_name_red_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_name_red_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_name_red_2.setLineWidth(1)
        self.label_name_red_2.setMidLineWidth(0)
        self.label_name_red_2.setScaledContents(False)
        self.label_name_red_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name_red_2.setObjectName("label_name_red_2")

        self.label_region_red_2.setGeometry(QtCore.QRect(40, 550, 800, 450))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_region_red_2.sizePolicy().hasHeightForWidth())
        self.label_region_red_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gotham")
        font.setPointSize(40)
        self.label_region_red_2.setFont(font)
        self.label_region_red_2.setAutoFillBackground(False)
        self.label_region_red_2.setStyleSheet("background-color: none;\n, color: white;")
        self.label_region_red_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_region_red_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_region_red_2.setLineWidth(1)
        self.label_region_red_2.setMidLineWidth(0)
        self.label_region_red_2.setScaledContents(False)
        self.label_region_red_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_region_red_2.setObjectName("label_region_red_2")

        self.frame_red2.raise_()
        self.frame_white2.raise_()
        self.line2.raise_()
        self.matchName2.raise_()

        self.retranslateUi(Form22)
        QtCore.QMetaObject.connectSlotsByName(Form22)

    def retranslateUi(self, Form22):
        _translate = QtCore.QCoreApplication.translate
        Form22.setWindowTitle(_translate("Form22", " "))
        self.matchName2.setText(_translate("Form22", "Татами №# М/Ж - возраст"))
        self.label_name_white_2.setText(_translate("Form22", "Фамилия"))
        self.label_region_white_2.setText(_translate("Form22", "НАИМЕНОВАНИЕ региона"))
        self.label_region_red_2.setText(_translate("Form22", "НАИМЕНОВАНИЕ региона"))
        self.label_name_red_2.setText(_translate("Form22", "Фамилия"))


class KataQual_SecondWindow(QWidget, KataQual_SecondWindow_Ui):
    def __init__(self):
        super().__init__()
        self.setupUi2(self)


class KataQual_MainWindow_Ui(object):
    def setupUi(self, Form21):
        Form21.setObjectName("Form21")
        Form21.setEnabled(True)
        Form21.setFixedSize(900, 500)
        Form21.setWindowOpacity(1.0)
        Form21.setToolTipDuration(-1)
        Form21.setStatusTip("")
        Form21.setStyleSheet("background-color: rgb(255, 255, 255);")

        self.KumiteButton = QtWidgets.QPushButton(Form21)
        self.KataFinalButton = QtWidgets.QPushButton(Form21)
        self.MenuButton = QtWidgets.QPushButton(Form21)
        self.label_matchName1 = QtWidgets.QLabel(Form21)
        self.label_matchName2 = QtWidgets.QLabel(Form21)
        self.matchName1 = QtWidgets.QLineEdit(Form21)
        self.line1 = QtWidgets.QFrame(Form21)
        self.frame_red1 = QtWidgets.QFrame(Form21)
        self.label_name_red_1 = QtWidgets.QLabel(self.frame_red1)
        self.label_region_red_1 = QtWidgets.QLabel(self.frame_red1)
        self.frame_white1 = QtWidgets.QFrame(Form21)
        self.label_name_white_1 = QtWidgets.QLabel(self.frame_white1)
        self.label_region_white_1 = QtWidgets.QLabel(self.frame_white1)
        self.pushButton_clearData = QtWidgets.QPushButton(Form21)
        self.pushButton_NewCategory = QtWidgets.QPushButton(Form21)
        self.pushButton_showData = QtWidgets.QPushButton(Form21)
        self.comboBox_age = QtWidgets.QComboBox(Form21)
        self.frame_sex = QtWidgets.QFrame(Form21)
        self.male = QtWidgets.QRadioButton(self.frame_sex)
        self.female = QtWidgets.QRadioButton(self.frame_sex)
        self.sex_1 = QtWidgets.QLabel(Form21)
        self.age_1 = QtWidgets.QLabel(Form21)
        self.comboBox_name_red_1 = QtWidgets.QComboBox(Form21)
        self.comboBox_name_white_1 = QtWidgets.QComboBox(Form21)
        self.name_red_1 = QtWidgets.QLabel(Form21)
        self.name_white_1 = QtWidgets.QLabel(Form21)
        self.lineEdit_name_red_1 = QtWidgets.QLineEdit(Form21)
        self.lineEdit_region_red_1 = QtWidgets.QLineEdit(Form21)
        self.lineEdit_name_white_1 = QtWidgets.QLineEdit(Form21)
        self.lineEdit_region_white_1 = QtWidgets.QLineEdit(Form21)

        self.label_matchName1.setGeometry(QtCore.QRect(20, 0, 405, 15))
        self.label_matchName1.setStyleSheet("font-family: Gotham-Light; font-size: 10pt;")
        self.label_matchName1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_matchName1.setObjectName("label_matchName1")

        self.label_matchName2.setGeometry(QtCore.QRect(20, 45, 700, 15))
        self.label_matchName2.setStyleSheet("color: grey; font-family: Gotham-Light; font-size: 10pt;")
        self.label_matchName2.setObjectName("label_matchName2")

        self.matchName1.setGeometry(QtCore.QRect(20, 15, 405, 30))
        self.matchName1.setStyleSheet("background-color: rgb(252, 252, 252); "
                                      "font-family: Gotham-Light; font-size: 15pt;")
        self.matchName1.setAlignment(QtCore.Qt.AlignCenter)
        self.matchName1.setObjectName("matchName1")

        self.MenuButton.setGeometry(QtCore.QRect(765, 5, 110, 20))
        self.MenuButton.setStyleSheet("background-color: rgb(242, 242, 242); font-family: Gotham-Light;"
                                        "font-size: 10pt;")
        self.MenuButton.setObjectName("MenuButton")

        self.KataFinalButton.setGeometry(QtCore.QRect(765, 30, 110, 20))
        self.KataFinalButton.setStyleSheet("background-color: rgb(242, 242, 242); "
                                      "font-family: Gotham-Light; font-size: 10pt;")
        self.KataFinalButton.setObjectName("KataFinalButton")

        self.KumiteButton.setGeometry(QtCore.QRect(765, 55, 110, 20))
        self.KumiteButton.setStyleSheet("background-color: rgb(242, 242, 242); font-family: Gotham-Light;"
                                        "font-size: 10pt;")
        self.KumiteButton.setObjectName("KumiteButton")

        self.line1.setGeometry(QtCore.QRect(447, 80, 6, 150))
        font = QtGui.QFont()
        font.setKerning(True)
        self.line1.setFont(font)
        self.line1.setLineWidth(1)
        self.line1.setMidLineWidth(6)
        self.line1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")

        self.frame_red1.setGeometry(QtCore.QRect(475, 80, 400, 150))
        self.frame_red1.setStyleSheet("background-color: rgb(255, 222, 219);")
        self.frame_red1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_red1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_red1.setObjectName("frame_red1")

        self.label_name_red_1.setGeometry(QtCore.QRect(20, 20, 360, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_name_red_1.sizePolicy().hasHeightForWidth())
        self.label_name_red_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gotham")
        font.setPointSize(25)
        self.label_name_red_1.setFont(font)
        self.label_name_red_1.setAutoFillBackground(False)
        self.label_name_red_1.setStyleSheet("background-color: none;")
        self.label_name_red_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_name_red_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_name_red_1.setLineWidth(1)
        self.label_name_red_1.setMidLineWidth(0)
        self.label_name_red_1.setScaledContents(False)
        self.label_name_red_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name_red_1.setObjectName("label_name_red_1")

        self.label_region_red_1.setGeometry(QtCore.QRect(20, 70, 360, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_region_red_1.sizePolicy().hasHeightForWidth())
        self.label_region_red_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gotham")
        font.setPointSize(15)
        self.label_region_red_1.setFont(font)
        self.label_region_red_1.setAutoFillBackground(False)
        self.label_region_red_1.setStyleSheet("background-color: none;")
        self.label_region_red_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_region_red_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_region_red_1.setLineWidth(1)
        self.label_region_red_1.setMidLineWidth(0)
        self.label_region_red_1.setScaledContents(False)
        self.label_region_red_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_region_red_1.setObjectName("label_region_red_1")

        self.frame_white1.setGeometry(QtCore.QRect(25, 80, 400, 150))
        self.frame_white1.setStyleSheet("background-color: white")
        self.frame_white1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_white1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_white1.setObjectName("frame_white1")

        self.label_name_white_1.setGeometry(QtCore.QRect(20, 20, 360, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_name_white_1.sizePolicy().hasHeightForWidth())
        self.label_name_white_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gotham")
        font.setPointSize(25)
        self.label_name_white_1.setFont(font)
        self.label_name_white_1.setAutoFillBackground(False)
        self.label_name_white_1.setStyleSheet("background-color: none;")
        self.label_name_white_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_name_white_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_name_white_1.setLineWidth(1)
        self.label_name_white_1.setMidLineWidth(0)
        self.label_name_white_1.setScaledContents(False)
        self.label_name_white_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_name_white_1.setObjectName("label_name_white_1")

        self.label_region_white_1.setGeometry(QtCore.QRect(20, 70, 360, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_region_white_1.sizePolicy().hasHeightForWidth())
        self.label_region_white_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Gotham")
        font.setPointSize(15)
        self.label_region_white_1.setFont(font)
        self.label_region_white_1.setAutoFillBackground(False)
        self.label_region_white_1.setStyleSheet("background-color: none;")
        self.label_region_white_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_region_white_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_region_white_1.setLineWidth(1)
        self.label_region_white_1.setMidLineWidth(0)
        self.label_region_white_1.setScaledContents(False)
        self.label_region_white_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_region_white_1.setObjectName("label_region_white_1")

        self.pushButton_clearData.setGeometry(QtCore.QRect(475, 330, 200, 35))
        self.pushButton_clearData.setStyleSheet("background-color: rgb(62, 106, 225); font-family: Gotham-Light;"
                                       "color: white; font-size: 15pt;")
        self.pushButton_clearData.setObjectName("pushButton_clearData")

        self.pushButton_NewCategory.setGeometry(QtCore.QRect(775, 320, 100, 45))
        font = QtGui.QFont()
        font.setFamily("Gotham-Light")
        font.setPointSize(10)
        self.pushButton_NewCategory.setFont(font)
        self.pushButton_NewCategory.setObjectName("pushButton_NewCategory")

        self.pushButton_showData.setGeometry(QtCore.QRect(175, 330, 250, 35))
        self.pushButton_showData.setStyleSheet("background-color: rgb(62, 106, 225); font-family: Gotham-Light;"
                                       "color: white; font-size: 15pt;")
        self.pushButton_showData.setObjectName("pushButton_showData")

        self.comboBox_age.setEnabled(False)
        self.comboBox_age.setGeometry(QtCore.QRect(480, 400, 111, 22))
        self.comboBox_age.setStyleSheet("background-color: rgb(242, 242, 242)")
        self.comboBox_age.setObjectName("comboBox_age")

        self.frame_sex.setGeometry(QtCore.QRect(270, 400, 151, 25))
        self.frame_sex.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_sex.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_sex.setObjectName("frame_sex")

        self.male.setGeometry(QtCore.QRect(20, 0, 40, 25))
        font = QtGui.QFont()
        font.setFamily("Gotham")
        font.setPointSize(15)
        self.male.setFont(font)
        self.male.setObjectName("male")

        self.female.setGeometry(QtCore.QRect(90, 0, 40, 25))
        font = QtGui.QFont()
        font.setFamily("Gotham")
        font.setPointSize(15)
        self.female.setFont(font)
        self.female.setObjectName("female")

        self.sex_1.setGeometry(QtCore.QRect(330, 380, 50, 13))
        self.sex_1.setStyleSheet("color: black; font-family: Gotham-Bold; font-size: 10pt;")
        self.sex_1.setAlignment(QtCore.Qt.AlignCenter)
        self.sex_1.setObjectName("sex_1")

        self.age_1.setGeometry(QtCore.QRect(480, 380, 111, 13))
        self.age_1.setStyleSheet("color: grey; font-family: Gotham-Light; font-size: 10pt;")
        self.age_1.setAlignment(QtCore.Qt.AlignCenter)
        self.age_1.setObjectName("age_1")

        self.comboBox_name_red_1.setEnabled(False)
        self.comboBox_name_red_1.setGeometry(QtCore.QRect(510, 450, 350, 25))
        self.comboBox_name_red_1.setStyleSheet("background-color: rgb(242, 242, 242)")
        self.comboBox_name_red_1.setObjectName("comboBox_name_red_1")

        self.comboBox_name_white_1.setEnabled(False)
        self.comboBox_name_white_1.setGeometry(QtCore.QRect(40, 450, 350, 25))
        self.comboBox_name_white_1.setStyleSheet("background-color: rgb(242, 242, 242)")
        self.comboBox_name_white_1.setObjectName("comboBox_name_white_1")

        self.name_red_1.setGeometry(QtCore.QRect(510, 430, 350, 16))
        self.name_red_1.setStyleSheet("color: grey; font-family: Gotham-Light; font-size: 10pt;")
        self.name_red_1.setAlignment(QtCore.Qt.AlignCenter)
        self.name_red_1.setObjectName("name_red_1")

        self.name_white_1.setGeometry(QtCore.QRect(40, 430, 350, 16))
        self.name_white_1.setStyleSheet("color: grey; font-family: Gotham-Light; font-size: 10pt;")
        self.name_white_1.setAlignment(QtCore.Qt.AlignCenter)
        self.name_white_1.setObjectName("name_white_1")

        self.lineEdit_name_red_1.setGeometry(QtCore.QRect(510, 240, 340, 30))
        self.lineEdit_name_red_1.setStyleSheet("background-color: rgb(252, 252, 252);"
                                             "font-family: Gotham-Light; font-size: 15pt;")
        self.lineEdit_name_red_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_name_red_1.setObjectName("lineEdit_name_red_1")

        self.lineEdit_region_red_1.setGeometry(QtCore.QRect(530, 290, 300, 30))
        self.lineEdit_region_red_1.setStyleSheet("background-color: rgb(252, 252, 252);"
                                               "font-family: Gotham-Light; font-size: 10pt;")
        self.lineEdit_region_red_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_region_red_1.setObjectName("lineEdit_region_red_1")

        self.lineEdit_name_white_1.setGeometry(QtCore.QRect(50, 240, 340, 30))
        self.lineEdit_name_white_1.setStyleSheet("background-color: rgb(252, 252, 252);"
                                             "font-family: Gotham-Light; font-size: 15pt;")
        self.lineEdit_name_white_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_name_white_1.setObjectName("lineEdit_name_white_1")

        self.lineEdit_region_white_1.setGeometry(QtCore.QRect(70, 290, 300, 30))
        self.lineEdit_region_white_1.setStyleSheet("background-color: rgb(252, 252, 252);"
                                               "font-family: Gotham-Light; font-size: 10pt;")
        self.lineEdit_region_white_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_region_white_1.setObjectName("lineEdit_region_white_1")

        self.frame_red1.raise_()
        self.line1.raise_()
        self.frame_white1.raise_()
        self.pushButton_clearData.raise_()
        self.pushButton_NewCategory.raise_()
        self.pushButton_showData.raise_()
        self.comboBox_age.raise_()
        self.frame_sex.raise_()
        self.sex_1.raise_()
        self.age_1.raise_()
        self.comboBox_name_red_1.raise_()
        self.comboBox_name_white_1.raise_()
        self.name_red_1.raise_()
        self.name_white_1.raise_()
        self.MenuButton.raise_()
        self.KataFinalButton.raise_()
        self.KumiteButton.raise_()
        self.label_matchName1.raise_()
        self.label_matchName2.raise_()
        self.matchName1.raise_()


        self.retranslateUi(Form21)
        QtCore.QMetaObject.connectSlotsByName(Form21)

    def retranslateUi(self, Form21):
        _translate = QtCore.QCoreApplication.translate
        Form21.setWindowTitle(_translate("Form21", "PC. Ката по флажкам"))
        self.label_matchName1.setText(_translate("Form21", '<b>Заголовок</b>'))
        self.label_matchName2.setText(_translate("Form21", 'Любой текст, после которого ставится <b>запятая</b>, не меняется программой'))
        self.matchName1.setText(_translate("Form21", "Татами №#, М/Ж - возраст"))
        self.MenuButton.setText(_translate("Form21", "Главное меню"))
        self.KataFinalButton.setText(_translate("Form21", "Ката финал"))
        self.KumiteButton.setText(_translate("Form21", "Кумите"))
        self.label_name_red_1.setText(_translate("Form21", "Фамилия"))
        self.label_region_red_1.setText(_translate("Form21", "НАИМЕНОВАНИЕ региона"))
        self.label_name_white_1.setText(_translate("Form21", "Фамилия"))
        self.label_region_white_1.setText(_translate("Form21", "НАИМЕНОВАНИЕ региона"))
        self.pushButton_clearData.setText(_translate("Form21", "Очистить данные"))
        self.pushButton_NewCategory.setText(_translate("Form21", "Новая \n категория"))
        self.pushButton_showData.setText(_translate("Form21", "Показать на экране"))
        self.male.setText(_translate("Form21", "М"))
        self.female.setText(_translate("Form21", "Ж"))
        self.sex_1.setText(_translate("Form21", "Пол"))
        self.age_1.setText(_translate("Form21", "Возраст"))
        self.name_red_1.setText(_translate("Form21", "Выберите спортсмена"))
        self.name_white_1.setText(_translate("Form21", "Выберите спортсмена"))
        self.lineEdit_name_red_1.setText(_translate("Form21", "АКА. Введите имя спортсмена"))
        self.lineEdit_region_red_1.setText(_translate("Form21", "АКА. Введите регион"))
        self.lineEdit_name_white_1.setText(_translate("Form21", "СИРО. Введите имя спортсмена"))
        self.lineEdit_region_white_1.setText(_translate("Form21", "СИРО. Введите регион"))


class KataQual_MainWindow(QWidget, KataQual_MainWindow_Ui):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

        self.KataQual_SecondWindow = KataQual_SecondWindow()

    def openSecondWin(self):
        self.KataQual_SecondWindow.show()

    def closeSecondWin(self):
        self.KataQual_SecondWindow.hide()

    def clearKataData(self):
        self.KataQual_SecondWindow.label_name_white_2.setText("Фамилия")
        self.KataQual_SecondWindow.label_region_white_2.setText("НАИМЕНОВАНИЕ региона")
        self.KataQual_SecondWindow.label_region_red_2.setText("НАИМЕНОВАНИЕ региона")
        self.KataQual_SecondWindow.label_name_red_2.setText("Фамилия")
        self.label_name_red_1.setText("Фамилия")
        self.label_region_red_1.setText("НАИМЕНОВАНИЕ региона")
        self.label_name_white_1.setText("Фамилия")
        self.label_region_white_1.setText("НАИМЕНОВАНИЕ региона")

    def NewCategory(self):
        self.KataQual_SecondWindow.label_name_white_2.setText("Фамилия")
        self.KataQual_SecondWindow.label_region_white_2.setText("НАИМЕНОВАНИЕ региона")
        self.KataQual_SecondWindow.label_region_red_2.setText("НАИМЕНОВАНИЕ региона")
        self.KataQual_SecondWindow.label_name_red_2.setText("Фамилия")
        self.label_name_red_1.setText("Фамилия")
        self.label_region_red_1.setText("НАИМЕНОВАНИЕ региона")
        self.label_name_white_1.setText("Фамилия")
        self.label_region_white_1.setText("НАИМЕНОВАНИЕ региона")
        self.comboBox_age.clear()
        self.comboBox_name_red_1.clear()
        self.comboBox_name_white_1.clear()
        self.comboBox_age.setEnabled(False)
        self.comboBox_age.setStyleSheet("background-color: rgb(242, 242, 242)")
        self.comboBox_name_red_1.setEnabled(False)
        self.comboBox_name_red_1.setStyleSheet("background-color: rgb(242, 242, 242)")
        self.comboBox_name_white_1.setEnabled(False)
        self.comboBox_name_white_1.setStyleSheet("background-color: rgb(242, 242, 242)")
        self.male.setAutoExclusive(False)
        self.male.setChecked(False)
        self.female.setAutoExclusive(False)
        self.female.setChecked(False)
        self.age_1.setStyleSheet("color: grey; font-family: Gotham-Light; font-size: 10pt;")
        self.name_red_1.setStyleSheet("color: grey; font-family: Gotham-Light; font-size: 10pt;")
        self.name_white_1.setStyleSheet("color: grey; font-family: Gotham-Light; font-size: 10pt;")
        self.lineEdit_name_red_1.setText("АКА. Введите имя спортсмена")
        self.lineEdit_region_red_1.setText("АКА. Введите регион")
        self.lineEdit_name_white_1.setText("СИРО. Введите имя спортсмена")
        self.lineEdit_region_white_1.setText("СИРО. Введите регион")
        # self.comboBox_age.addItems(None)
        # self.comboBox_name_red_1.addItems(None)
        # self.comboBox_name_white_1.addItems(None)

    def setDataKata(self):
        self.KataQual_SecondWindow.matchName2.setText(self.matchName1.text())
        self.label_name_red_1.setText(self.lineEdit_name_red_1.text())
        self.label_region_red_1.setText(self.lineEdit_region_red_1.text())
        self.KataQual_SecondWindow.label_name_red_2.setText(self.lineEdit_name_red_1.text())
        self.KataQual_SecondWindow.label_region_red_2.setText(self.lineEdit_region_red_1.text())
        print('длина имя (red) в пикселях', self.label_name_red_1.fontMetrics().boundingRect(self.label_name_red_1.text()).width())
        self.label_name_white_1.setText(self.lineEdit_name_white_1.text())
        self.label_region_white_1.setText(self.lineEdit_region_white_1.text())
        self.KataQual_SecondWindow.label_name_white_2.setText(self.lineEdit_name_white_1.text())
        self.KataQual_SecondWindow.label_region_white_2.setText(self.lineEdit_region_white_1.text())
        print('длина имя (white) в пикселях', self.label_name_white_1.fontMetrics().boundingRect(self.label_name_white_1.text()).width())


