self.KataQual_SecondWindow.label_name_white_2.setText("Фамилия")
self.KataQual_SecondWindow.label_region_white_2.setText("НАИМЕНОВАНИЕ региона")
self.KataQual_SecondWindow.label_region_red_2.setText("НАИМЕНОВАНИЕ региона")
self.KataQual_SecondWindow.label_name_red_2.setText("Фамилия")

self.label_name_red_1.setText("Фамилия")
self.label_region_red_1.setText("НАИМЕНОВАНИЕ региона")
self.label_name_white_1.setText("Фамилия")
self.label_region_white_1.setText("НАИМЕНОВАНИЕ региона")
self.comboBox_age.setEnabled(False)
self.comboBox_age.clear()
self.male.setChecked(False)
self.female.setChecked(False)
self.comboBox_name_red_1.setEnabled(False)
self.comboBox_name_red_1.clear()
self.comboBox_name_white_1.setEnabled(False)
self.comboBox_name_white_1.clear()
